name: 'QGIS Plugin Upload'
description: 'Uploads a release .zip fiel to the QGIS plugin repository'
author: 'Efstathios Lymperis'

# Define your inputs here.
inputs:
  release-zip-path:
    description: 'Repository path to the release .zip file'
    required: true

# Define your outputs here.
outputs:
  success:
    description: 'Plugin url'

runs:
  using: node20
  main: dist/index.js
